### ISSUE TITLE
JavaScript running and checking

### ISSUE THREAD

**Issue by Y19461947** [daniel-munro/pbnify#1]
Hello, excuse me, I have allowed the JavaScript running and checking of the browser, but I still can't enter https://pbnify.com/ which shows that your browser must be able to retrieve and run JavaScript libraries to use pbnify

**Comment by daniel-munro** [comment]
Yes. What is preventing your browser from doing that?

**Comment by ruhlmcu** [comment]
I am no longer able to get the technical color detail that was previously displayed with the palette.

**Comment by daniel-munro** [comment]
I'm not sure how that's related to the issue you're commenting in. Does the "show color info" button appear below the palette, and if so, what happens when you click it?

**Comment by ruhlmcu** [comment]
Sorry. My bad. It has nothing to do with this issue. User error. Also the button is there and it works.  Again, user error.
