### ISSUE TITLE
Request adding Chinese Localization

### ISSUE THREAD

**Issue by sgsq** [daniel-munro/pbnify#4]
In China due to some reason we have no access to google ajax .
![2020-08-01 18-28-15 的屏幕截图](https://user-images.githubusercontent.com/54973059/89099840-c9562a80-d424-11ea-923e-8e05adadccc3.png)

So I changed the CDN to jsdeliver. Also I did the translation.
Here's the link. Will you consider adding it to your webpage?
<a href="https://sqhs.club/pbnify/">Chinese Simplified</a>
https://sqhs.club/pbnify/

**Comment by daniel-munro** [comment]
Thanks for doing that! I've added the link to the top of the page. I've also decided to replace the Angular and Bootstrap CDNs with included scripts to avoid any CDN issues.

**Comment by sgsq** [comment]
You are welcome.
