### ISSUE TITLE
How do I adjust the outline width

### ISSUE THREAD

**Issue by harun-dinler** [daniel-munro/pbnify#5]
Hello, I follow your project closely and it helps me a lot. I need to make the outlines a little thicker, but I don't know how I can do this. Can you help me?

**Comment by daniel-munro** [comment]
Are you asking how to do that at pbnify.com, or how to edit the source code to do that? If the first, it isn't possible. If the second, you'd want to edit the outline() and/or neighborsSame() functions in processImage.js, which draw the lines pixel by pixel.
