### ISSUE TITLE
Changing the size of numbers to fit in small areas

### ISSUE THREAD

**Issue by lucasurielperez** [daniel-munro/pbnify#6]
Hi Dan! I'm making custom changes to your code since a couple of months. And I'm trying now to set a range of sizes to the numbers according to the size of regions they belong to.

For that i modified getLabelLoc function to send a "size of region" variable along with label, x and y. in processimage.js
Then read it on displayResults and print the correct size for each number.

The problem I'm having is that no matter what i change in processimage.js it's not working, i tried even deleting processimage.js and the app keeps working!!!! so i think its related to some lack of knowledge i have.

Do you have an idea of what I'm doing wrong??? this is getting me crazy.

**Comment by daniel-munro** [comment]
Hello, maybe it's using a cached version of processImage.js? If so, it could be due to the fact that it's called from another js script as a web worker rather than being referenced in the HTML directly. Maybe try it in another browser or after clearing the cache for the site.

**Comment by lucasurielperez** [comment]
i was that! edge was caching processimage.js. Thanks!!
