### ISSUE TITLE
Request i18n

### ISSUE THREAD

**Issue by songsammy** [daniel-munro/pbnify#7]
I have a few friends who would like to translate the project to some languages.
So will you consider i18n the project? Thanks.

**Comment by daniel-munro** [comment]
Would that involve changes to the source code, or for me to just add links to the translated versions as I did for the Chinese translation? I can definitely do the latter, and maybe the former if it isn't too much work.

**Comment by songsammy** [comment]
The former. Search for "Angular i18n" on the internet for more details.
Trust me, it deserves the trouble.

**Comment by daniel-munro** [comment]
I see. Thanks for the suggestion, but I don't have time to make those changes, so someone else will have to do it.
