### ISSUE TITLE
Is there a C/C++ version that can be parallelized for performance

### ISSUE THREAD

**Issue by bibrakc** [daniel-munro/pbnify#8]
Is there any parallel implementation that uses multi-core processors or GPUs to speed up the computation? Basically is there is a way to get the color points and then have those input to a C/C++ program that reads the image that will be a good starting point. I can easily parallelize the computation on CPUs and GPUs if there is an interest.

**Comment by daniel-munro** [comment]
This is the only version that I'm involved with and am aware of.
